//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.18 at 12:30:50 PM SAMT 
//


package xmlstate.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for gray complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gray">
 *   &lt;complexContent>
 *     &lt;extension base="{}red">
 *       &lt;sequence>
 *         &lt;element name="isHungry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hungryCounter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="predatorTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="eatingTime" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gray", propOrder = {
    "isHungry",
    "hungryCounter",
    "predatorTime",
    "eatingTime"
})
public class Gray
    extends Red
{

    protected boolean isHungry;
    @XmlElement(required = true)
    protected BigInteger hungryCounter;
    @XmlElement(required = true)
    protected BigInteger predatorTime;
    protected boolean eatingTime;

    /**
     * Gets the value of the isHungry property.
     * 
     */
    public boolean isIsHungry() {
        return isHungry;
    }

    /**
     * Sets the value of the isHungry property.
     * 
     */
    public void setIsHungry(boolean value) {
        this.isHungry = value;
    }

    /**
     * Gets the value of the hungryCounter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHungryCounter() {
        return hungryCounter;
    }

    /**
     * Sets the value of the hungryCounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHungryCounter(BigInteger value) {
        this.hungryCounter = value;
    }

    /**
     * Gets the value of the predatorTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPredatorTime() {
        return predatorTime;
    }

    /**
     * Sets the value of the predatorTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPredatorTime(BigInteger value) {
        this.predatorTime = value;
    }

    /**
     * Gets the value of the eatingTime property.
     * 
     */
    public boolean isEatingTime() {
        return eatingTime;
    }

    /**
     * Sets the value of the eatingTime property.
     * 
     */
    public void setEatingTime(boolean value) {
        this.eatingTime = value;
    }

}
