//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.18 at 12:30:50 PM SAMT 
//


package xmlstate.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for red complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="red">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lifeTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="breedingTime" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="canBreeding" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mustDie" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "red", propOrder = {
    "type",
    "lifeTime",
    "breedingTime",
    "canBreeding",
    "mustDie",
    "x",
    "y"
})
@XmlSeeAlso({
    Gray.class
})
public class Red {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected BigInteger lifeTime;
    @XmlElement(required = true)
    protected BigInteger breedingTime;
    protected boolean canBreeding;
    protected boolean mustDie;
    @XmlElement(required = true)
    protected BigInteger x;
    @XmlElement(required = true)
    protected BigInteger y;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the lifeTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLifeTime() {
        return lifeTime;
    }

    /**
     * Sets the value of the lifeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLifeTime(BigInteger value) {
        this.lifeTime = value;
    }

    /**
     * Gets the value of the breedingTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBreedingTime() {
        return breedingTime;
    }

    /**
     * Sets the value of the breedingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBreedingTime(BigInteger value) {
        this.breedingTime = value;
    }

    /**
     * Gets the value of the canBreeding property.
     * 
     */
    public boolean isCanBreeding() {
        return canBreeding;
    }

    /**
     * Sets the value of the canBreeding property.
     * 
     */
    public void setCanBreeding(boolean value) {
        this.canBreeding = value;
    }

    /**
     * Gets the value of the mustDie property.
     * 
     */
    public boolean isMustDie() {
        return mustDie;
    }

    /**
     * Sets the value of the mustDie property.
     * 
     */
    public void setMustDie(boolean value) {
        this.mustDie = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setX(BigInteger value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setY(BigInteger value) {
        this.y = value;
    }

}
